### ISSUE TITLE
Unable to build locally

### ISSUE THREAD

**Issue by huijing** [interledger/interledger.org-frontend#16]
When running `yarn build` locally, the following error occurs:

```
[=   ] info  - Generating static pages (5/13)TypeError: Cannot read properties of undefined (reading 'startsAt')
    at ParagraphScheduleDay (/Users/huijing/Sites/interledger/website/nextjs/.next/server/chunks/3148.js:176:103)
    at Wc (/Users/huijing/Sites/interledger/website/nextjs/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
    at Zc (/Users/huijing/Sites/interledger/website/nextjs/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
    at Z (/Users/huijing/Sites/interledger/website/nextjs/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at $c (/Users/huijing/Sites/interledger/website/nextjs/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
    at bd (/Users/huijing/Sites/interledger/website/nextjs/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
    at Z (/Users/huijing/Sites/interledger/website/nextjs/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
    at $c (/Users/huijing/Sites/interledger/website/nextjs/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
    at bd (/Users/huijing/Sites/interledger/website/nextjs/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
    at Z (/Users/huijing/Sites/interledger/website/nextjs/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)

Error occurred prerendering page "/%2Fsummit". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: Cannot read properties of undefined (reading 'startsAt')
    at ParagraphScheduleDay (/Users/huijing/Sites/interledger/website/nextjs/.next/server/chunks/3148.js:176:103)
    at Wc (/Users/huijing/Sites/interledger/website/nextjs/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
    at Zc (/Users/huijing/Sites/interledger/website/nextjs/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
    at Z (/Users/huijing/Sites/interledger/website/nextjs/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at $c (/Users/huijing/Sites/interledger/website/nextjs/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
    at bd (/Users/huijing/Sites/interledger/website/nextjs/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
    at Z (/Users/huijing/Sites/interledger/website/nextjs/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
    at $c (/Users/huijing/Sites/interledger/website/nextjs/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
    at bd (/Users/huijing/Sites/interledger/website/nextjs/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
    at Z (/Users/huijing/Sites/interledger/website/nextjs/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
info  - Generating static pages (13/13)

> Export encountered errors on following paths:
        /[...slug]: /%2Fsummit
```

**Comment by huijing** [comment]
Will no longer be relevant when https://github.com/interledger/interledger.org-v4 goes live.
